### ISSUE TITLE
Alsa-Device Auswahl

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/RustPager#11]
Nicht immer ist die Default-Karte die richtige..

**Comment by 7h0ma5** [comment]
Spricht etwas dagegen, die Default-Karte zu ändern? Ein Text-Feld zur Eingabe des Devices in der Art "hw:0,0" wäre einfach, eine Liste wesentlich komplizierter.

**Comment by dh3wr** [comment]
Vielleicht kann man mit http://diwic.github.io/alsa-rs-docs/alsa/device_name/index.html die vorhandenen Devices einlesen? Sonst über ein geparste Ausgaben von aplay -L oder aplay -l ?  Eine Dropdown-Liste wäre schon schöner...

**Comment by dh3wr** [comment]
Ich habe nun 2 Anfragen zu diesem Thema. Könnte man nicht auf die schnelle ein Textfeld in die Weboberfläche einbauen, wo man den Soundcard-Identifier als Klartext eingeben kann und dieser wird dann hier
https://github.com/rwth-afu/RustPager/blob/master/src/transmitter/audio/transmitter.rs Line 68 ff. :
````
       let mut child = Command::new("aplay")
            .stdin(Stdio::piped())
            .args(&["-t", "raw", "-N", "-f", "U8", "-c", "1"])
            .args(&["-r", &*format!("{}", SAMPLE_RATE)])
            .spawn()
            .expect("Failed to start aplay");
````
eingabaut?

**Comment by dg1kwa** [comment]
Frage: Was MUSS man in diesem Feld den jetzt eingeben? Bei gar nicht zieht default?

**Comment by stephensworld** [comment]
das würde mich auch interessieren.

Grüße
Stephan

**Comment by dh3wr** [comment]
Dazu kann sich am besten @7h0ma5 äußern.

**Comment by 7h0ma5** [comment]
Wenn nichts in das Feld eingegeben wird, wird das `default`-Device verwendet. Wenn man eine bestimmte Soundkarte verwenden will, muss man das im Format `plughw:[device id],[subdevice id]` angeben, zum Beispiel `plughw:1,0`.
