### ISSUE TITLE
ADF7012 not Ready

### ISSUE THREAD

**Issue by rtausend** [rwth-afu/RustPager#14]
Bei Aussendungen von einem Raspager kommt häufig die Meldung das der ADF7012 not ready ist:

INFO Received Message { id: 4, mtype: AlphaNum, speed: Baud(1200), addr: 4512, func: AlphaNum, data: "1!*TlzqfsMjof" }
INFO Received Message { id: 5, mtype: AlphaNum, speed: Baud(1200), addr: 4512, func: AlphaNum, data: "1+*SXUI.BGV" }
INFO Received Message { id: 6, mtype: AlphaNum, speed: Baud(1200), addr: 4512, func: AlphaNum, data: "1**JHGT!Jogp" }
INFO Received Message { id: 7, mtype: AlphaNum, speed: Baud(1200), addr: 4512, func: AlphaNum, data: "1\"*TlzqfsTqput" }
WARN ADF7012 not ready
INFO Transmission completed.
INFO Received Message { id: 8, mtype: Numeric, speed: Baud(1200), addr: 2504, func: Numeric, data: "141200 130117" }
INFO Transmitting...
WARN ADF7012 not ready
INFO Transmission completed.
INFO Received Message { id: 9, mtype: Numeric, speed: Baud(1200), addr: 2504, func: Numeric, data: "141400 130117" }
INFO Transmitting...
INFO Transmission completed.

Ist das ein Bug?

**Comment by 7h0ma5** [comment]
Das ist eigentlich nur eine Debug-Ausgabe. Wenn der Raspager aktiviert wird, lockt die PLL manchmal nicht beim ersten Versuch, dann wird diese Warnung ausgegeben. Es wird maximal fünf mal versucht, die PLL zu locken, das heißt, erst wenn diese Warnung fünf mal direkt hintereinander käme, dann wäre das Senden nicht möglich.
