### ISSUE TITLE
LED-Ansteuerung für Connected/Running/OnAir

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/RustPager#20]
Es wäre schön, wenn man GPIO-Ports definieren könnte, mit denen man Frontplatten-LEDs ansteuern könnte. Eine freie Auswahl der GPIO-Ports oder auch "null" für "nicht vorhanden/gewünscht" wäre super. Einmal für den C9000, aber auch für die RasPagerDigi-Variante.

**Comment by dh3wr** [comment]
Funktionswunschliste:
- RustPager läuft
- RustPager ist mit Core verbunden
- RustPager sendet (wenn möglich)

**Comment by dk4pa** [comment]
Wäre es evtl. auch möglich ein Nextion Display einzubinden?

**Comment by dh3wr** [comment]
@dk4pa Ich habe mit @7h0ma5 gesprochen. Wenn dann als externes Programm, welches sich als Websocket-Client mit dem Rustpager verbindet und dann die Weboberfläche emuliert. Ich bestelle mir mal ein solche Display und einen USB->3,3V TTL Wandler. Magst du die Software schreiben? Es gibt hier https://github.com/eidheim/Simple-WebSocket-Server einen Websocket Client in C++.

**Comment by dk4pa** [comment]
@dh3wr Würde ich sofort machen, leider habe ich null Erfahrung was C++ oder ähnliches angeht.

**Comment by dh3wr** [comment]
@7h0ma5 Macht es Sinn, die GPIO-LEDs auch mit einem externen Programm zu steuern, dass sich als Websocket-Client verbindet?

**Comment by dh3wr** [comment]
Nextion Issue ausgelagert: https://github.com/rwth-afu/RustPagerNextion

**Comment by 7h0ma5** [comment]
@dh3wr Das würde auf jeden Fall Sinn machen. Vor allem kann dann sichergestellt werden, dass die LED, die anzeigt, ob der RustPager läuft, auf jeden Fall ausgeht, auch wenn der RustPager durch irgendeinen Grund gekillt wird und die LED nicht selbst ausschalten kann. Und ich muss mir keine Gedanken zur Implementierung machen 😉 Ein Problem ist nur, dass dann je nach gewähltem Transmitter zwei Programme gleichzeitig auf die GPIO-Pins zugreifen. Da müsste man testen, ob das ohne Probleme möglich ist.

**Comment by dh3wr** [comment]
@7h0ma5 ok Thomas, ich schreibe mal ein C++ Programm dazu

**Comment by dh3wr** [comment]
LED Issue ausgelagert, damit hier zu. https://github.com/rwth-afu/RustPagerLED
