### ISSUE TITLE
ADF7012 not ready

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/RustPager#23]
info Received Message { id: 0, mtype: AlphaNum, speed: Baud(1200), addr: 12345, func: AlphaNum, data: "1fsfasfhjkas hfjklahskj hfklashjkldfhajkshf jkahsjkdfhjklashdfasdfa" }

info Transmitting...

info Transmission completed.

info Received Message { id: 0, mtype: AlphaNum, speed: Baud(1200), addr: 12345, func: AlphaNum, data: "ashjk hfjkal hsdjkfhakjs lhdkfjl hasjkhfjklashjkdfhlkajl shjkflhaskjlhdjkf lhasdfasdfasdfa" }

info Transmitting...

warn ADF7012 not ready

**Comment by 7h0ma5** [comment]
Meinst du damit die Warnung "ADF7012 not ready"? Wenn ja, dann habe ich das in #14 schon mal beantwortet. Das hat schon einen Sinn, warum das eine Warnung und kein Error ist. Damit das nicht immer zur Verwirrung führt, kann ich das aber mal ändern in eine Debug-Ausgabe.
