### ISSUE TITLE
Detected Raspberry Pi 1 Model B Rev. 2 Failed to map GPIO

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/RustPager#24]
pi@raspberrypi:~/RustPager/target/release $ ./rustpager 
RustPager 0.3.3
Copyright (c) 2017 RWTH Amateurfunkgruppe

This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute
and modify it under the conditions of the GNU GPL v3 or later.
<https://www.gnu.org/licenses/gpl-3.0.txt>

INFO - Listening for 44.225.164.3 on port 1337.
INFO - Initializing C9000 transmitter...
INFO - Detected Raspberry Pi 1 Model B Rev. 2
thread '<unnamed>' panicked at 'Failed to map GPIO', /buildslave/rust-buildbot/slave/nightly-dist-rustc-cross-host-linux/build/src/libcore/option.rs:715
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by 7h0ma5** [comment]
Das Programm muss als root ausgeführt werden, da Memory Mapping von beliebigen Adressen, wie zum Beispiel den GPIO-Registern, nur für root erlaubt ist.
