### ISSUE TITLE
Fehlermeldung auf Raspberry Pi Modell 1B

### ISSUE THREAD

**Issue by phl0** [rwth-afu/RustPager#30]
Ich bekome beim Start auf einem Raspberry Pi der ersten Generation (1B) eine Fehlermeldung:

![bildschirmfoto vom 2017-02-08 23-06-52](https://cloud.githubusercontent.com/assets/7112907/22759610/54b06782-ee53-11e6-8f2a-5ea914bd2447.png)

Ist das evtl. ein Bug? Wie kann ich das verifizieren bzw. analysieren?

**Comment by 7h0ma5** [comment]
Siehe #24.

**Comment by phl0** [comment]
Danke für die Info. Hätte ich selbst drauf kommen können ... *banghead*
