### ISSUE TITLE
Compile error client auth branch

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/RustPager#32]
pi@raspagergm1200:~/RustPager $ cargo build --release
   Compiling rustpager v0.3.3 (file:///home/pi/RustPager)
error: use of unstable library feature 'duration_checked_ops' (see issue #35774)
  --> src/pocsag/timeslots.rs:56:21
   |
56 |         match start.checked_sub(now) {
   |                     ^^^^^^^^^^^
   |
   = help: add #![feature(duration_checked_ops)] to the crate attributes to enable

error: aborting due to previous error

error: Could not compile `rustpager`.

**Comment by 7h0ma5** [comment]
Bitte den Compiler mit `rustup update` auf die neuste Version updaten.
