### ISSUE TITLE
Neuer Name für RustPager

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/RustPager#34]
Nachdem der Name RustPager ja nun nicht optimal ist, würde ich hier gerne mögliche Alternativen diskutieren.
Da die Software ja alle Hardware-Varianten unterstützt, würde ich etwas wie
UniversalPager oder UnifiedPager
oder ähnlich vorschlagen.

**Comment by 7h0ma5** [comment]
Liste der bisherigen Vorschläge:

- UniversalPager
- UnifiedPager
- UniPager
- HamPocPager (von @MicManders auf Twitter)
- HAMpager (von @FaLanKeFu auf Twitter)
- AllPager (von @DK4PA auf Twitter)
- PocPager (von @DK4PA auf Twitter)

**Comment by 7h0ma5** [comment]
Der neue Name von RustPager wird **UniPager**. Alle nötigen Änderungen sind schon im debian-Branch vorhanden, mit dem gleichzeitig eine wesentlich einfachere Installation über ein APT-Repository möglich wird.

**Comment by dh3wr** [comment]
Ok, ich ändere den CQDL Beitrag entsprechend
