### ISSUE TITLE
Compile error Compiling num-traits command not found

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/RustPager#39]
DL6KL schreibt: 
Beim Compilieren der Software habe ich nachdem der rustpager 0.4 compiliert war folgende Meldung bekommen:
````Compiling num-traits
command not found
````
Ist das schlimm?

**Comment by 7h0ma5** [comment]
Das sind leider zu wenig Informationen um damit irgendetwas anfangen zu können. Sinnvoll wäre mindestens eine Kopie aller Ausgaben des Kompiliervorgangs.
