### ISSUE TITLE
"Failed to map GPIO", /checkout/src/libcore/option.rs:785

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/RustPager#40]
DL6KL schreibt:
Wenn ich einen Restart mache kommt diese Meldung:
````unname panicked at "Failad to map GPIO", /checkout/src/libcore/option.rs:785````

Welche Hardwareplattform dem zugrunde liegt, ist angefragt. Evtl. ein x86?

**Comment by 7h0ma5** [comment]
Ja, entweder ist das kein Raspberry Pi oder RustPager wird nicht als root ausgeführt (siehe #24), wobei ich auf letzteres tippe. Die Fehlermeldung sieht man nämlich nur, wenn der Scheduler gestartet wird, das heißt im Webinterface nur, wenn man auf Restart drückt.

**Comment by dh3wr** [comment]
Es ist ein Raspi P1 Model B Rev.2
Zumindest das ist nun geklärt. Der Root-Status kommt noch.
