### ISSUE TITLE
Minor: Bezeichung Raspager in RaspagerV1 im Pull-Downmenü ändern

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/RustPager#43]
Eher nebensächlich, nur der Konsistenz wegen.

**Comment by phl0** [comment]
@dh3wr: Sowas?

![screenshot from 2017-03-09 20-49-00](https://cloud.githubusercontent.com/assets/7112907/23767846/6133a58c-050a-11e7-94f0-b4f4ecfb2e99.png)

Code hier: https://github.com/phl0/RustPager/tree/RaspagerV1 Wenn gewünscht, mache ich dafür auch n PR. Ggf. muss ich das vorher noch überarbeiten, wenn #49 vorher gemerged wird.

**Comment by phl0** [comment]
Hab meinen Branch wieder gelöscht.
