### ISSUE TITLE
Auf Raspi 2 compiliert nicht

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/RustPager#50]
Lieber Ralf,

leider habe ich es nicht geschafft, RustPager auf meinem RPI2 zu compilieren. Auch ein "frisches" Jessie-Image hilft nicht. Ich erhalte immer folgende Fehlermeldung:

   Compiling tiny_http v0.5.8
   Compiling ws v0.6.0
   Compiling serde_codegen_internals v0.14.1
   Compiling serde_derive v0.9.10
   Compiling rustpager v0.4.0 (file:///home/pi/RustPager)
error: proc-macro derive panicked
  --> src/status.rs:10:10
   |
10 | #[derive(Serialize, Clone, Copy, Debug)]
   |          ^^^^^^^^^
   |
   = help: message: already mutably borrowed: BorrowError

error: Could not compile `rustpager`.

To learn more, run the command again with --verbose.

**Comment by 7h0ma5** [comment]
Siehe #42
