### ISSUE TITLE
"Could not compile rustpager, proc-macro drive panicked"

### ISSUE THREAD

**Issue by MurrayBozinsky** [rwth-afu/RustPager#57]
Hardware: RasPi3B
Software: RaspiJessy vom 15.3., rust vom 15.3., RustPager 0.42 von gerade eben

pi@DM0AI-7:~/RustPager $ cargo build --release --verbose
.....

Fresh num v0.1.37
       Fresh chrono v0.2.25
       Fresh tiny_http v0.5.8
   Compiling rustpager v0.4.2 (file:///home/pi/RustPager)
     Running `rustc --crate-name rustpager src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=923b2cb92bf3d5f0 -C extra-filename=-923b2cb92bf3d5f0 --out-dir /home/pi/RustPager/target/release/deps -L dependency=/home/pi/RustPager/target/release/deps --extern tiny_http=/home/pi/RustPager/target/release/deps/libtiny_http-41b7c462fcb4d2bd.rlib --extern serial=/home/pi/RustPager/target/release/deps/libserial-2ae09162fcdfddf8.rlib --extern serde=/home/pi/RustPager/target/release/deps/libserde-8d100abf080b884d.rlib --extern serde_json=/home/pi/RustPager/target/release/deps/libserde_json-bf30fe9b648bf22a.rlib --extern serde_derive=/home/pi/RustPager/target/release/deps/libserde_derive-b60b2ec3c5df2de1.so --extern raspi=/home/pi/RustPager/target/release/deps/libraspi-ac555867c676e4c7.rlib --extern ws=/home/pi/RustPager/target/release/deps/libws-2ce1cc82a13b2e33.rlib --extern net2=/home/pi/RustPager/target/release/deps/libnet2-8d6db02178fc0f61.rlib --extern lazy_static=/home/pi/RustPager/target/release/deps/liblazy_static-5a2ead901945c047.rlib --extern log=/home/pi/RustPager/target/release/deps/liblog-973d2302a68c7b2e.rlib`
error: proc-macro derive panicked
  --> src/status.rs:10:10
   |
10 | #[derive(Serialize, Clone, Copy, Debug)]
   |          ^^^^^^^^^
   |
   = help: message: already mutably borrowed: BorrowError

error: Could not compile `rustpager`.

Caused by:
  process didn't exit successfully: `rustc --crate-name rustpager src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=923b2cb92bf3d5f0 -C extra-filename=-923b2cb92bf3d5f0 --out-dir /home/pi/RustPager/target/release/deps -L dependency=/home/pi/RustPager/target/release/deps --extern tiny_http=/home/pi/RustPager/target/release/deps/libtiny_http-41b7c462fcb4d2bd.rlib --extern serial=/home/pi/RustPager/target/release/deps/libserial-2ae09162fcdfddf8.rlib --extern serde=/home/pi/RustPager/target/release/deps/libserde-8d100abf080b884d.rlib --extern serde_json=/home/pi/RustPager/target/release/deps/libserde_json-bf30fe9b648bf22a.rlib --extern serde_derive=/home/pi/RustPager/target/release/deps/libserde_derive-b60b2ec3c5df2de1.so --extern raspi=/home/pi/RustPager/target/release/deps/libraspi-ac555867c676e4c7.rlib --extern ws=/home/pi/RustPager/target/release/deps/libws-2ce1cc82a13b2e33.rlib --extern net2=/home/pi/RustPager/target/release/deps/libnet2-8d6db02178fc0f61.rlib --extern lazy_static=/home/pi/RustPager/target/release/deps/liblazy_static-5a2ead901945c047.rlib --extern log=/home/pi/RustPager/target/release/deps/liblog-973d2302a68c7b2e.rlib` (exit code: 101)
pi@DM0AI-7:~/RustPager $ 

Was mache ich falsch ?

**Comment by 7h0ma5** [comment]
Das Problem tritt nicht reproduzierbar auf einzelnen Raspberry Pi auf. Hier gibt es bereits ein Issue für dieses Problem: #42

Die einzige Lösung ist momentan eine fertig kompilierte Binary zu verwenden, die man hier herunterladen kann: https://github.com/rwth-afu/RustPager/releases
