### ISSUE TITLE
Nagios Ausgabe, ob Master connected ist

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/RustPager#6]
Am schönsten natürlich eine Nagios-kompatibel formatierte Ausgabe in einer Datei (Ort siehe #5 )

MasterConnection OK - Connected to <IP>:<Port>   oder
MasterConnection CRITICAL - Not connected

**Comment by rtausend** [comment]
Für Zabbix wäre das natürlich auch genial :)

**Comment by dh3wr** [comment]
@rtausend : Hast du ein Beispiel, wie die Ausgabe aussehen muss?

**Comment by rtausend** [comment]
ich hab gerade geschaut, dafür gibts wohl keinen Standard. Ich nehm was ich bekomm und parse mir das dann. Vielen Dank

**Comment by dh3wr** [comment]
Also da verwenden wir dann wohl auch einfach das Websocket. Client wäre hier https://blog.grandcentrix.net/a-command-line-websocket-client/
@7h0ma5 sind die Websocket-Befehle irgendwo dokumentiert? Vielleicht im Wiki des Github-Repos?

**Comment by 7h0ma5** [comment]
Ich habe mal damit angefangen, ist aber noch unvollständig: https://github.com/rwth-afu/RustPager/wiki/Websocket-Protocol

**Comment by dh3wr** [comment]
@7h0ma5 Danke für die Infos. Ich habe unter https://github.com/rwth-afu/RustPagerNagios ein passenden Plugin geschrieben. Info dazu unter https://www.afu.rwth-aachen.de/projekte/funkruf-pager-pocsag/rustpager#nagios
Damit können wir das schließen.
