### ISSUE TITLE
Logfile

### ISSUE THREAD

**Issue by rtausend** [rwth-afu/RustPager#8]
Hallo,

es wäre super wenn man irgendwie ein Logfile ausgeben könnte z.B. nach /var/log/rustpager.log (oder konfigurierbar)

Im moment könnte man einen Fehler der nachts passiert glaube ich nicht nachvollziehen oder?

Danke und Gruß

**Comment by 7h0ma5** [comment]
Es wäre kein Problem das zu Implementieren, aber da das Log auch auf der Standardausgabe ausgegeben wird, könnte man die komplette Ausgabe auch mit dem Befehl "./RustPager &>> rustpager.log" in die Datei rustpager.log umleiten. Wenn man systemd benutzt, dann geht es auch so schon, da kann man sich das Log einfach mit "sudo journalctl -u rustpager" anzeigen lassen.

**Comment by rtausend** [comment]
Verstehe das Argument, nur zum "mal schnell" durchsuchen dürfte ein echtes Logfile doch praktischer sein oder bin ich nur zu "old scool" :) Ich hab das bei mir jetzt so implementiert das er über den systemd gestartet wird, funktioniert auch sehr gut

**Comment by daccle** [comment]
Hmm, @7h0ma5 hat gezeigt, wie es mit systemd/jounalctl geht. IMHO kann das hier geschlossen werden.
