### ISSUE TITLE
RustPager stirbt nach Config-Speichern

### ISSUE THREAD

**Issue by rtausend** [rwth-afu/RustPager#9]
Hallo,

(version 0.3.1)

wenn ich nach einer gewissen laufzeit (2-3h) des RustPagers eine Configänderung mache stirbt der Dienst.

Jan 10 10:40:15 raspberry.afu.ducktales.net rustpager[468]: INFO - Received Message { id: 98, mtype: AlphaNum, speed: Baud(1200), addr: 4512, func: AlphaNum, data: "1**JHGT!Jogp" }
Jan 10 10:40:15 raspberry.afu.ducktales.net rustpager[468]: INFO - Received Message { id: 99, mtype: AlphaNum, speed: Baud(1200), addr: 4512, func: AlphaNum, data: "1\"*TlzqfsTqput" }
Jan 10 10:42:00 raspberry.afu.ducktales.net rustpager[468]: INFO - Received Message { id: 100, mtype: Numeric, speed: Baud(1200), addr: 2504, func: Numeric, data: "104200   100117" }
Jan 10 10:44:00 raspberry.afu.ducktales.net rustpager[468]: INFO - Received Message { id: 101, mtype: Numeric, speed: Baud(1200), addr: 2504, func: Numeric, data: "104400   100117" }
Jan 10 10:44:22 raspberry.afu.ducktales.net rustpager[468]: INFO - Config updated. Initiating restart.
Jan 10 10:44:22 raspberry.afu.ducktales.net rustpager[468]: INFO - Waiting for the scheduler to terminate...
Jan 10 10:44:22 raspberry.afu.ducktales.net rustpager[468]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', /buildslave/rust-buildbot/slave/nightly-dist-rustc-cross-host-linux/build/src/libcore/result.rs:845
Jan 10 10:44:22 raspberry.afu.ducktales.net systemd[1]: rustpager.service: main process exited, code=exited, status=101/n/a
Jan 10 10:44:22 raspberry.afu.ducktales.net systemd[1]: Unit rustpager.service entered failed state.

**Comment by 7h0ma5** [comment]
So wie das Log aussieht war zu diesem Zeitpunkt bereits das Gleiche Problem wie in #7 aufgetreten, das heißt der Scheduler-Thread lief nicht mehr. Durch das Speichern der Konfiguration wird dem Scheduler ein Kommando zum Neustart geschickt, wenn dieser aber nicht mehr existiert, kommt es zu einem Fehler. Dadurch darf natürlich nicht das ganzen Programm abstürzen, was mit Commit 44b792b behoben wurde.

Da im Log kein genauer Backtrace steht, könnte die Ursache theoretisch auch noch woanders liegen. Um einen Backtrace mit ausgeben zu lassen, muss man Rust mit der Umgebungsvariablen `RUST_BACKTRACE=1` ausführen. In der Shell sieht das so aus: `RUST_BACKTRACE=1 ./rustpager`. Mit systemd muss man die Zeile `Environment=RUST_BACKTRACE=1` im Abschnitt `[Service]` einfügen und danach `sudo systemctl daemon-reload` und `sudo systemctl restart rustpager` ausführen.
